export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_ALERTS = "GET_ALERTS";
export const CLEAR_ALERTS = "CLEAR_ALERTS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_USERS = "GET_USERS";
export const GET_USER = "GET_USER";

export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRY = "GET_COUNTRY";

export const GET_CITIES = "GET_CITIES";
export const GET_CITY = "GET_CITY";

export const GET_DISTRICTS = "GET_DISTRICTS";
export const GET_DISTRICT = "GET_DISTRICT";

export const GET_NATIONALITIES = "GET_NATIONALITIES";
export const GET_NATIONALITY = "GET_NATIONALITY";

export const GET_FIELD_TYPE = "GET_FIELD_TYPE";
export const GET_FIELD_TYPES = "GET_FIELD_TYPES";

export const GET_GAME_TYPE = "GET_GAME_TYPE";
export const GET_GAME_TYPES = "GET_GAME_TYPES";

export const GET_SPECIAL_REQUEST = "GET_SPECIAL_REQUEST";
export const GET_SPECIAL_REQUESTS = "GET_SPECIAL_REQUESTS";

export const GET_PLAYING_POSITION = "GET_PLAYING_POSITION";
export const GET_PLAYING_POSITIONS = "GET_PLAYING_POSITIONS";

export const GET_MAIN_AD = "GET_MAIN_AD";
export const GET_MAIN_ADS = "GET_MAIN_ADS";

export const GET_PROVIDED_SERVICE = "GET_PROVIDED_SERVICE";
export const GET_PROVIDED_SERVICES = "GET_PROVIDED_SERVICES";

export const GET_STADIUM = "GET_STADIUM";
export const GET_STADIUMS = "GET_STADIUMS";

export const GET_VIDEO = "GET_VIDEO";
export const GET_VIDEOS = "GET_VIDEOS";

export const GET_PAGE = "GET_PAGE";

export const GET_PERMISSION = "GET_PERMISSION";
export const GET_PERMISSIONS = "GET_PERMISSIONS";

// ENDDDDDDDDDDDDD

export const GET_LEAD_SOURCES = "GET_LEAD_SOURCES";
export const GET_LEAD_TYPES = "GET_LEAD_TYPES";

export const GET_LEAD_INFO = "GET_LEAD_INFO";
export const SAVE_LEAD = "SAVE_LEAD";
export const GET_LEAD_INFO_LOADING = "GET_LEAD_INFO_LOADING";
export const GET_LEAD_INFO_UNLOADING = "GET_LEAD_INFO_UNLOADING";
export const GET_ALL_LEADS = "GET_ALL_LEADS";
